name: A first test workflow
on: 
  push

jobs: 
  My-first-CI:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with: 
        python-version: 3.10
    - name: Install dependencies 
      run: pip -m install pytest
    - name: Run unit tests
      run: pytest
